## JWT
jwt.secret=7H5v9pR3wX2yQ4uL6mN8oB0vC2xE4zF6gH8iJ0kL2mN4oP6qR8sT0uV2wX4yZ6aB8cD0eF2gH4iJ6kL8mN0oP2qR4sT6uV8wX0yZ
jwt.expiration.ms=3600000
jwt.refresh.expiration.ms=604800000
# Autres propriétés (MySQL, mail, OTP...)
spring.datasource.url=jdbc:mysql://localhost:3307/recrutement?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.format_sql=true
server.ssl.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
cloudinary.cloud-name=dpxbv4jhv
cloudinary.api-key=636218147963452
cloudinary.api-secret=8V8bYctxyj59UM1YZdCSbchOBss
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bctstage@gmail.com
spring.mail.password=joqr xsky tqha ixlz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.upload.dir=uploads/quiz
cv.scorer.script=src/main/resources/python/cv_scorer.py
cv.scorer.model.dir=src/main/resources/python/models/bert_bct

# OTP
otp.expiration.minutes=2
otp.max.attempts=10
otp.block.minutes=2
logging.level.org.springframework.security=DEBUG
logging.level.com.bct.recrutement.security.JwtService=DEBUG
logging.level.com.bct.recrutement.config.JwtAuthenticationFilter=DEBUG
logging.level.com.bct.recrutement.config.JwtUtils=DEBUG
logging.level.org.springframework.scheduling=DEBUG
logging.level.org.springframework.aop=DEBUG
openrouter.api.key=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
openrouter.model=openrouter/free
openrouter.app.name=BCT-Recrutement
openrouter.site.url=http://localhost:5173
//quiz.generator.url=http://localhost:5000
//quiz.generator.port=5000
#groq.api.key=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
groq.api.key=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
groq1.api.key=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
//flask.face.service.url=http://localhost:5002
//flask.face.service.port=5002
flask.face.script=src/main/resources/python/face_verification_service.py
app.base-url=http://localhost:3000
spring.websocket.path=/ws
//flask.cv.url=http://localhost:5003
python.executable=src/main/resources/python/venv/Scripts/python.exe
ml.router.url=http://localhost:5000
quiz.generator.url=${ml.router.url}
flask.face.service.url=${ml.router.url}
flask.cv.url=${ml.router.url}
flask.face.service.port=5000
quiz.generator.port=5000